### PR TITLE
Feature/service manager 3

### PR DESCRIPTION
**Pull request by acelaya**
This updates the component to depend on zend-servicemanager v3.

This is what I've changed:
- Updated the zendframework/zend-servicemanager component version
- The Zend\ServiceManager v3 doesn't need a `Zend\ServiceManager\Config` instance anymore, so I've removed it
- The `Zend\ServiceManager\ServiceLocatorInterface` extends from `Interop\Container\ContainerInterface` in this version, so I've removed the implementation from the `RKA\ZsmSlimContainer\Container` class
- I have removed some return statements, since v3 does not implement a fluid interface anymore and returns nothing.
- I have updated the `offsetUnset` method that was calling a protected method that has been removed.

It has been small changes.
I haven't added any test, because I've seen there are no other tests, and everything can be fairly tested by using the example app.
However, If you want me to add some tests, I could do it.

### CODE REVIEW

**Comment by akrabat** [comment]
Thanks! I'll look at it soon

**Comment by acelaya** [comment]
Is there any update on this?

**Comment by akrabat** [comment]
Hoping to get to it soon!

**Comment by acelaya** [comment]
Perfect! :-)

**Comment by akrabat** [comment]
Got to it! Thanks very much :)

**Comment by akrabat** [comment]
Note that I've bumped the version number to 2.0.0 for this change.

**Comment by acelaya** [comment]
You are welcome! Thanks for merging.

**Pull request merged**
